#!/bin/bash

./run_rxvt 58-bak 2> rxvt-tmp-out
cat rxvt-tmp-out | grep -v BEGIN | grep -v "urxvt: unable" | grep -v "locate urxvt.pm" > rxvt-out
java -jar ~/temp/downloads/js/rhino/rhino1_6R7/js.jar spdr_test.js 58-bak > rxvt-js-out
#python report.py

#head -n 200 rxvt-out |  sed 's/ *$//g' | sed 's/^ *//g'  > rxvt-out-for-ediff
#head -n 200 rxvt-js-out |sed 's/ *$//g' | sed 's/^ *//g'  > rxvt-js-out-for-ediff

# echo "RXVT OUTPUT " > report.txt
# cat rxvt-out | sort | uniq -c | sort -n >>  report.txt
# echo "JS OUTPUT " >> report.txt
# cat rxvt-js-out  | sort | uniq -c | sort -n  >> report.txt

# cat report.txt
