#!/bin/bash

#simple example from  http://www.grymoire.com/Unix/Sed.html#uh-nl
(echo a;echo x;echo y) | gsed '/x[ ]*$/ {
N
s:x\n:x:
}'

#adding in some more spice
(echo a;echo x;echo y) | gsed '/x[ ]*$/ {
N
s:x\ny:x:
}'

#getting to the crux of my problem
(echo else;echo {;echo y) | gsed '/else*$/ {
N
s:else\n{:else{:
}'

#adding in some spice
(echo "  else  ";echo  {;echo y) | gsed '/else *$/ {
N
s:else *\n{:else{:
}'

#padding the closing brace with space
(echo "  else  ";echo  " { ";echo y) | gsed '/else *$/ {
N
s:else *\n *{:else{:
}'

#layering in alternation
(echo "  if ()  ";echo  " { "; echo "  else  ";echo  " { ";echo y) | gsed -r '/(else|\)) *$/ {
N
s:(else|\)) *\n *[{]:\1{:
}'

#layering in alternation and some reptition
(echo "  if ()   ";echo  " { "; echo "  else  ";echo  " { ";echo y) | gsed -r '/(else|\)) *$/ {
N
s:(else|\)) *\n *[{]:\1{:
}'

#layering in tabs
(echo "  if ()   ";echo  "	{ "; echo "  else  ";echo  " { ";echo y) | gsed -r '/(else|\)) *$/ {
N
s:(else|\))[ \t]*\n[ \t]*[{]:\1{:
}'

block_end="(else|\))"
#adding shell variables
(echo "  if ()   ";echo  "	{ "; echo "  else  ";echo  " { ";echo y) | gsed -r '/'"$block_end"' *$/ {
N
s:'"$block_end"'[ \t]*\n[ \t]*[{]:\1{:
}'

block_start="(else|\))"
echo " adding shell variables "
(echo "  if ()   ";echo  "	{ "; echo "  else  ";echo  " { ";echo y) | gsed -r '/'"$block_start"' *$/ {
N
s:'"$block_start"'[ \t]*\n[ \t]*[{]:\1{:
}'
